language: ruby
rvm:
 - 2.3.4
 - jruby

services:
  - postgresql

script:
  - bundle exec rspec spec

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bin/rails db:migrate 
