language: ruby
rvm:
 - 2.3
 - jruby
 - rbx-2

services:
  - postgresql

script:
  - bundle exec rspec spec

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bin/rails db:migrate RAILS_ENV=test
